//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Resume = new HashSet<Resume>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Başlık { get; set; }
        public string Text { get; set; }
        public string Date { get; set; }
        public string Verified { get; set; }
    
        public virtual ICollection<Resume> Resume { get; set; }
        public virtual User User { get; set; }
    }
}
